# SIMULACOES COM simula.neutra.step.dd (DEMONIO DE DARWIN)

#simulacao original (simula.neutra.step)
oi<-simula.neutra.step(20,20,10,5,NULL,NULL,50000,10)
oi.1<-simula.neutra.step(20,20,10,5,NULL,NULL,50000,10)
oi.2<-simula.neutra.step(20,20,10,5,NULL,NULL,50000,10)
riqueza.tempo <- apply(oi$sp.list,2,conta.sp)
riqueza.tempo.1 <- apply(oi.1$sp.list,2,conta.sp)
riqueza.tempo.2 <- apply(oi.2$sp.list,2,conta.sp)
plot(riqueza.tempo,type="l",xlab="Tempo",ylab="Riqueza",main="Variação na riqueza (original - rep1)")
plot(riqueza.tempo.1,type="l",xlab="Tempo",ylab="Riqueza",main="Variação na riqueza (original - rep2)")
plot(riqueza.tempo.2,type="l",xlab="Tempo",ylab="Riqueza",main="Variação na riqueza (original - rep3)")
tab<-fert.t1(oi$sp.list,oi$sementes,mean)
tab.1<-fert.t1(oi.1$sp.list,oi.1$sementes,mean)
tab.2<-fert.t1(oi.2$sp.list,oi.2$sementes,mean)
matplot(t(tab),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação no número de propágulos (original - rep1)")
matplot(t(tab.1),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação no número de propágulos (original - rep2)")
matplot(t(tab.2),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação no número de propágulos (original - rep3)")

#simulacao demonio de darwin (simula.neutra.step.dd)
oi2<-simula.neutra.step.dd(20,20,10,5,NULL,NULL,50000,10)
oi2.1<-simula.neutra.step.dd(20,20,10,5,NULL,NULL,50000,10)
oi2.2<-simula.neutra.step.dd(20,20,10,5,NULL,NULL,50000,10)
riqueza.tempo2 <- apply(oi2$sp.list,2,conta.sp)
riqueza.tempo2.1 <- apply(oi2.1$sp.list,2,conta.sp)
riqueza.tempo2.2 <- apply(oi2.2$sp.list,2,conta.sp)
plot(riqueza.tempo2,type="l",xlab="Tempo",ylab="Riqueza",main="Variação na riqueza (demônio Darwin - rep1)")
plot(riqueza.tempo2.1,type="l",xlab="Tempo",ylab="Riqueza",main="Variação na riqueza (demônio Darwin - rep2)")
plot(riqueza.tempo2.2,type="l",xlab="Tempo",ylab="Riqueza",main="Variação na riqueza (demônio Darwin - rep3)")
tab2<-fert.t1(oi2$sp.list,oi2$sementes,mean)
tab2.1<-fert.t1(oi2.1$sp.list,oi2.1$sementes,mean)
tab2.2<-fert.t1(oi2.2$sp.list,oi2.1$sementes,mean)
matplot(t(tab2),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação no número de propágulos (demônio Darwin - rep1)")
matplot(t(tab2.1),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação no número de propágulos (demônio Darwin - rep2)")
matplot(t(tab2.2),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação no número de propágulos (demônio Darwin - rep3)")
tab2.prob<-fert.t1(oi2$sp.list,oi2$prob.morte,mean)
tab2.1.prob<-fert.t1(oi2.1$sp.list,oi2.1$prob.morte,mean)
tab2.2.prob<-fert.t1(oi2.2$sp.list,oi2.1$prob.morte,mean)
matplot(t(tab2.prob),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação na probabilidade de morte (demônio Darwin - rep1)")
matplot(t(tab2.1.prob),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação na probabilidade de morte (demônio Darwin - rep2)")
matplot(t(tab2.2.prob),type="l",xlab="Ciclo",ylab="",axes=T,main="Variação na probabilidade de morte (demônio Darwin - rep3)")
